name: Feature Request
description: Suggest a new program or new feature
labels: [ 'Feature' ]
body:
  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      multiple: true
      options:
        - New Program
        - Checker
        - Authorizer
        - Renamer
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: The preciser the better.
      placeholder: |
        For New Program: Describe the program's function and why it cannot be implemented with the existing programs.
        For New Feature: Describe the your ideas.
    validations:
      required: false
