name: Clear Workflow Records

permissions:
  actions: write

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow Filename'
        required: true
        type: string
      keep:
        description: 'Number of Records to Keep'
        type: number
        default: 0

jobs:
  Clear-Records:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: iamazeem/delete-workflow-runs-action@main
        with:
          workflow: '${{ inputs.name }}'
          keep: ${{ inputs.keep }}
