name: CMake

permissions:
  read-all

on:
  push:
    branch:
  release:
    types: [ published,edited ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7.0.1

    - name: Install NSIS
      run: choco install nsis -y

    - name: Deploy NSIS
      run: echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure CMake of Build
      if: github.event_name == 'release'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Build -G "MinGW Makefiles"

    - name: Configure CMake of Debug
      if: github.event_name != 'release'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"

    - name: Build
      run: cmake --build build

    - name: Create an Setup Wizard
      run: make -C build build
      
    - name: Deploy
      working-directory: build
      run: |
        $setup = Get-ChildItem -Filter "OpenVPNConfigManagerSetup-*.exe" | Select-Object -First 1
        if (-not $setup)
        {
          Write-Error "Package not found."
          exit 1
        }
        Start-Process -FilePath $setup.FullName -ArgumentList "/S" -Wait
        echo "C:\Program Files (x86)\OpenVPN Config Manager" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Test
      working-directory: build
      run: ctest -C Debug --output-on-failure --verbose

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name == 'workflow_dispatch'
      with:
        name: OpenVPN-Config-Manager-Release
        path: build/OpenVPNConfigManagerSetup-*.exe

    - name: Create attachments
      working-directory: build
      if: github.event_name == 'release'
      run : |
        make zip

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      permissions:
        contents: write
      if: github.event_name == 'release'
      with:
        file: build/*.{exe,zip}
        overwrite: true
        file_glob: true
        draft: false
